[package]
name = "rai-mods"
version = "0.0.0"
description = "Rai Pal"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
specta = "1.0.5"
tauri-specta = { version = "1.0.2", features = ["typescript"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.4.3"
keyvalues-serde = "0.1.0"
steamlocate = "1.2.1"
tauri = { version = "1.4.1", features = [] }
reqwest = "0.11.20"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = []
